version: "3"
services:
  # Create Hardhat container
  hardhat-docker: # Name of our service
    build:
      context: ./Contracts/
      dockerfile: Dockerfile.hardhat # path to dockerfile
    ports: # Port binding to host from docker container
      - "8545:8545" # Bind port 8545 of host to 8545 of container
    container_name: hardhat-docker
    restart: always # What to do if container crashes

  # Create Contract container
  contract: # Name of our service
    build:
      context: ./Contracts/
      dockerfile: Dockerfile.contract # path to dockerfile
    container_name: contract-docker
    depends_on:
      - hardhat-docker

  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend

  # Create backend container
  backend:
    # Create backend container
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always
