FROM node:18-alpine3.18

# Make folder to put our files in
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/contracts

WORKDIR /usr/src/app/contracts
# Copy package json and install dependencies
COPY package*.json ./
RUN npm install
# Copy our app
COPY . .

CMD ["npm", "run", "deploy:docker"]
